apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: python-api 
    env: canary
  name: python-api-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-api
        env: canary
    spec:
      containers:
      - image: quay.io/sir_rob/python_api:v1
        imagePullPolicy: IfNotPresent
        name: python-api
        ports:
        - containerPort: 5000 
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
